### ISSUE TITLE
Timestamp is 4 hours behind

### ISSUE THREAD

**Issue by justin-dx** [miyachan/torako#13]
I've just started a new instance with a fresh db and everything is getting archived correctly. However, the timestamp column is populated with a unix timestamp that is 4 hours behind what the current timestamp should be.
I'm not sure if this is a db config issue, but the db is set to UTC timezone.
Any ideas?

**Comment by miyachan** [comment]
torako is designed to be a drop-in replacement for [Asagi](https://github.com/eksopl/asagi) and therefore follows the Asagi convention of saving the `timestamp` field as a unix timestamp adjusted in the New York timezone. This is done as other legacy software, like FoolFuuka expects the timestamp in this "incorrect" format. 

As an extention, if `torako` detects a `unix_timestamp` column in the post table, it will populate the proper UNIX timestamp. If you are migrating from an older version you may need to add a `unix_timestamp` column if you are using the latest version of Torako:

```sql
ALTER TABLE `a` ADD COLUMN `unix_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
```

**Comment by justin-dx** [comment]
Okay that makes sense. I'm guessing I need a new db (or migration) to change this to UTC instead of just pointing torako at the same db and having it work.
