### ISSUE TITLE
[feature request] Ability to delete thread from your archive

### ISSUE THREAD

**Issue by bigretromike** [miyachan/torako#14]
I understand that from pure archivist point of view this is not needed, but any chance there is or it could be added ability to delete thread + media

**Comment by miyachan** [comment]
I'm not sure I understand; if you are running the software, you can just log into your mysql database and delete the thread yourself. Or you can use [FoolFuuka](https://github.com/bibanon/FoolFuuka) to moderate your archive.

Torako does not provide any management software.

**Comment by bigretromike** [comment]
Oh, I didnt know I could use FoolFuuka, im running 'ayase'.
Thank you for info I will look into it.
