### ISSUE TITLE
Not updating when thread is closed

### ISSUE THREAD

**Issue by justin-dx** [miyachan/torako#18]
The database should reflect that the thread has been archived but the %board%_threads.locked column is never set.
I'm not using database triggers, but that shouldn't matter because I can't find anything in the sql scripts that would update that field.

**Comment by miyachan** [comment]
My memory is fuzzy, but I don't think this is something asagi did either. Here is the commit where I removed setting the locked column:

https://github.com/miyachan/torako/commit/1234fa0d7b8bffd8da1bcd5a0e071ead0c48d642

**Comment by justin-dx** [comment]
I'll add it back in then :)
I think that's the best way, otherwise I gotta check post/image limit and/or timestamp to determine if a thread is dead.
I've never touched rust, but updating a dependency (mysql_async) and adding in the locked field shouldn't be to hard
