### ISSUE TITLE
Can't specify require_ssl on connection url

### ISSUE THREAD

**Issue by justin-dx** [miyachan/torako#19]
I'm trying to use a planetscale db as the backend and their connections require ssl. After trying to add the params to the MySql connection string, I've noticed that some are accepted, while `require_ssl` is rejected as `UnknownParameter`.
For example, the following are accepted:

- mysql://root:pass@localhost/db?prefer_socket=false
- mysql://root:pass@localhost/db?tcp_nodelay=false
 
While this is rejected:
- mysql://root:pass@localhost/db?require_ssl=true

Any ideas why

**Comment by miyachan** [comment]
The version of [mysql_async](https://github.com/blackbeam/mysql_async) that torako uses is `0.24.1` and it looks like ssl URL support was added in `0.31.3`

If there are no backwards incompatible changes, just bumping the version should enable ssl support.
