### ISSUE TITLE
First bits or Last Bits for the radix directory?

### ISSUE THREAD

**Issue by antonizoon** [miyachan/torako#6]
Radix directories are a necessary evil because of the limitations of directory listing, where there cannot be too many files in a single directory.

Initially, I had argued for using the last bits of the sha256 filename in the radix directories just like how futabilly and yuki.la did it, to be consistent with at least some demonstrated standard.

https://i1.yuki.la/1/07/4d05a123da4223d66a6f3183f7c4448d1cadfffdeeee4c9847c7f962d702c071.png

However, another team member argued that since git and Gitlab use the first bits of the sha256 filename instead, it is not necessarily a settled question, and using the first few bits of the filename may be a more obvious methodology.

https://docs.gitlab.com/ee/administration/repository_storage_types.html

The Futabilly developer argued that the reason he and others used the last bits he was convinced that because of issues like the Birthday problem, hash character distribution would not be equal if we used the first bits. 

However, link rot has lost the article that convinced him, but it must have been a very convincing article if he and yuki.la independently choose to do it. As it is a counterintuitive naming convention, there must be some good reason for it.

We should work this out once and for all before it starts getting used as a standard in production deployments.

**Comment by miyachan** [comment]
I’m not convinced the birthday problem applies here - or at least in the way that is mentioned. If all bits of a sha hash are meant to be somewhat random based on the input, it should matter if you use the first bits, last bits or middle bits - all of them will have the same properties.

In other words, the sha algorithm doesn’t place any importance on the position of the bits.

**Comment by antonizoon** [comment]
Yeah that's how it should be for sure. The real question then is now: should we switch to the first bits or the last bits?

**Comment by Suika** [comment]
Having to use the last bits makes any otther type of works outside of the DB and App(ayase) become more of a pain.
Files are never sorted properly. To figure out where files should be placed, you need extra steps. 
If the filename/hash is ever saved to the DB as text, you need to have reverse(END > START) index as not to trigger fill table scan. (Don't know if you can partially match a bin field)

It wouldn't be a problem if the files were saved without extensions, but that is not the case. Which forces you to take extra steps to get the bits.
There are a few more if I try to thing hard about it, but generally it makes no sense to use the last bits.

The distribution relatively flast in all directions. The most deviation between folders would bet ~10%, but that is to be expected with random results.
I'll provide results once I hash all my files, but it makes little sense to use the last bits.

**Comment by miyachan** [comment]
So given a `sha_sum` of `4d05a123da4223d66a6f3183f7c4448d1cadfffdeeee4c9847c7f962d702c071`, the resulting file would be `/4/05/4d05a123da4223d66a6f3183f7c4448d1cadfffdeeee4c9847c7f962d702c071.jpg`

**Comment by miyachan** [comment]
Fixed in 0.11.1
