### ISSUE TITLE
[feature request] Ability to scrap archives + addition 

### ISSUE THREAD

**Issue by bigretromike** [miyachan/torako#7]
I would love to see ability (if its not already there) scrap others online chan-archivers

Additional to that ability to merge them with "source"-chan. 

That way there could be a exchange between archives. 
I understand that there would be need for '/catalog/' endpoint and other things. 

Possible ?

**Comment by miyachan** [comment]
If I understand the request correctly, I'm not sure it makes sense for this project. What would it mean to scrape another chan-archive? Would it download the entirety of the other archive? Wouldn't a catalog endpoint of another chan-archive attempt to return every thread ever archived?

**Comment by bigretromike** [comment]
Simple example.

You want to archive chan, you got big server, lots of storage. But you would like to archive the content from before also. With normal chan, you can only start from now (everything that is available today), but you would like to populate your archive with already archived version just in case other archive die. So you would start grabbing current content from proper chan, but the historical content from other archive.

I hope this is more understandable.
